[build]
  command = "npm run build"
  publish = "public"

[[redirects]]
  from = "/showroom/nissan/qashqai-1-5-dci-2/ea61tvj"
  to = "/showroom"
  status = 301
  force = false

[[redirects]]
  from = "/favicon.ico"
  to = "/assets/images/favicon.ico"
  status = 301
  force = false

[[redirects]]
  from = "/.well-known"
  to = "/"
  status = 301
  force = false

[[redirects]]
  from = "/index.php"
  to = "/"
  status = 301
  force = false
